### ISSUE TITLE
I did not see any virtual machine on server to receive sdp offer and return sdp answer for client.

### ISSUE THREAD

**Issue by cedricVu** [roomrtc/signaling#6]

**Comment by vunb** [comment]
What type of network topology do you use ? If you are using type of `mesh`, please dont config to listen event message on the server:

```js
// do not config to listen this event
signalingServer.on('message', (client, msg) => {
    console.log('server receive message:', msg, client.id);
});
```

**Comment by cedricVu** [comment]
Thanks. So, i can use Signaling as SFU ?

**Comment by vunb** [comment]
No. It is just [Signaling](https://github.com/roomrtc/signaling/) server ! If you want to use SFU, you will need combining with a SFU server. I recommend you to use [ibc/mediasoup](https://github.com/ibc/mediasoup). It is quite easy to integrate with [Signaling](https://github.com/roomrtc/signaling/) and you can see the documation here https://mediasoup.org/

**Comment by vunb** [comment]
I have just created a simple media server here https://github.com/roomrtc/mediaserver
Please follow to see how it is implemented 🚼

**Comment by cedricVu** [comment]
Thanks so much.

2017-03-21 10:29 GMT+07:00 Nhữ Bảo Vũ <notifications@github.com>:
